version: '3.9'
services:

  users-service:
    build:
      context: ..
      dockerfile: ./docker/local/Dockerfile
    container_name: users-service
    image: example/users-service
    restart: unless-stopped
    environment:
      APP_ENV: "LOCAL"
    env_file:
      - ../.env.local
    entrypoint: sh -c "./main"
    ports:
      - "8080:8080"
    depends_on:
      postgres-users-service:
        condition: service_healthy
      users-service-migrate:
        condition: service_completed_successfully

  postgres-users-service:
    container_name: postgres-users-service
    image: postgres:15.2
    restart: always
    volumes:
      - users-service-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'users-service-db'
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  users-service-migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url postgres://user:pass@postgres-users-service:5432/users-service-db?sslmode=disable
    env_file:
      - ../.env.local
    volumes:
      - ../migrations/:/migrations
    depends_on:
      postgres-users-service:
        condition: service_healthy

volumes:
  users-service-data:
    driver: local