version: '3.9'
services:

  users-service-debug:
    build:
      context: ..
      dockerfile: ./docker/debug/Dockerfile
    container_name: users-service-debug
    image: example/users-service-debug
    restart: unless-stopped
    entrypoint: sh -c "/app/dlv --listen=:$${DELVE_PORT} --headless=true --api-version=2 --accept-multiclient exec /app/main"
    environment:
      APP_ENV: "LOCAL"
    env_file:
      - ../.env.local
    ports:
      - "8080:8080"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      postgres-users-service:
        condition: service_healthy

  postgres-users-service:
    container_name: database-users-service
    image: postgres:15.2
    restart: always
    volumes:
      - users-service-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'users-service-db'
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  users-service-data:
    driver: local